services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: logistics-crm:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      # Make sure the application listens to standard HTTP headers for HTTPS redirection (since it's behind a proxy)
      - TRUSTED_PROXIES=* 
    volumes:
      - ./storage/logs:/app/storage/logs
      - ./storage/app/public:/app/storage/app/public
    networks:
      - shared_network

networks:
  shared_network:
    external: true
